-- Time Travel and file safe!



-- Set the Roles, Warehouses and Databases
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

-- ===== Time Travel (Deleting some rows) =====

CREATE OR REPLACE TABLE DROP_TABLE (
    ID INT,
    NAME VARCHAR
);

INSERT INTO DROP_TABLE VALUES
(1, 'JOHN'),
(2, 'SAM'),
(3, 'ELAN'),
(4, 'MARK');

DELETE FROM DROP_TABLE
WHERE ID = 4;

SELECT * FROM DROP_TABLE
AT (OFFSET => -60 * 1);

SELECT * FROM DROP_TABLE
AT (TIMESTAMP => '2024-08-29 22:52:15.536 -0700'::TIMESTAMP_TZ);

SELECT * FROM DROP_TABLE
BEFORE (STATEMENT => '01b6b085-0000-b70f-0007-c56a0002eb16');

CREATE OR REPLACE TABLE DROP_TABLE_CLONE AS
SELECT * FROM DROP_TABLE
BEFORE (STATEMENT => '01b6b085-0000-b70f-0007-c56a0002eb16');
-- Set the Roles, Warehouses and Databases
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

-- ===== Time Travel (Deleting some rows) =====

CREATE OR REPLACE TABLE DROP_TABLE (
    ID INT,
    NAME VARCHAR
);

INSERT INTO DROP_TABLE VALUES
(1, 'JOHN'),
(2, 'SAM'),
(3, 'ELAN'),
(4, 'MARK');

DELETE FROM DROP_TABLE
WHERE ID = 4;

SELECT * FROM DROP_TABLE
AT (OFFSET => -60 * 1);

SELECT * FROM DROP_TABLE
AT (TIMESTAMP => '2024-08-29 22:52:15.536 -0700'::TIMESTAMP_TZ);

SELECT * FROM DROP_TABLE
BEFORE (STATEMENT => '01b6b085-0000-b70f-0007-c56a0002eb16');

CREATE OR REPLACE TABLE DROP_TABLE_CLONE AS
SELECT * FROM DROP_TABLE
BEFORE (STATEMENT => '01b6b085-0000-b70f-0007-c56a0002eb16');

TRUNCATE TABLE DROP_TABLE;

INSERT INTO DROP_TABLE
SELECT * FROM DROP_TABLE_CLONE;

DROP TABLE DROP_TABLE_CLONE;

SELECT * FROM DROP_TABLE;


-- ===== Dropping table, schema and database =====

DROP TABLE DROP_TABLE;

SELECT * FROM DROP_TABLE;

UNDROP TABLE DROP_TABLE;

DROP DATABASE MYDB;

UNDROP DATABASE MYDB;

USE SCHEMA MYDB.MYSCHEMA;

SHOW DATABASES;

SHOW SCHEMAS;

SHOW TABLES;

USE SCHEMA MYDB.MYSCHEMA;

ALTER TABLE DROP_TABLE
SET DATA_RETENTION_TIME_IN_DAYS = 1;


-- Set the Roles, Warehouses and Databases
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

-- ===== Zero copy cloning =====

-- Create a test db from actual db
CREATE OR REPLACE DATABASE test_mydb
CLONE mydb;

-- Drop the clone db
DROP DATABASE test_mydb;


